config/routes.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Rails.application.routes.draw do
  namespace 'squash', path: '' do
    # resources :projects, only: [ :new ]
    resources :projects do
      member { patch :rekey }
      resources :commits do
        member { get :context }
      end
      resources :environments, only: [ :index, :update ] do
        resources :bugs, except: [:new, :create, :edit] do
          collection { get :count }
          member { post :watch, :notify_deploy, :notify_occurrence }
          resources :occurrences, only: [:index, :show] do
            collection { get :count, :aggregate, :histogram }
          end
          resources :events, only: :index
          resources :comments, except: [:show, :new, :edit]
          resource :notification_threshold, only: [:create, :update, :destroy]
        end
      end
      resources :memberships, controller: 'project/memberships', only: [:index, :create, :update, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
      resource :membership, controller: 'project/membership', as: :my_membership, only: [:edit, :update, :destroy] do
        member { post :join }
        resources :emails, controller: 'emails', only: [:index, :create]
      end
    end

    constraints(id: /[^\/]+?/, format: 'html') do
      resources :users, only: :show
    end
    actions = [:index]
    actions << :create if Squash::Configuration.authentication.strategy == 'password'
    resources :users, only: actions

    actions = [:show]
    actions << :update if Squash::Configuration.authentication.strategy == 'password'
    resource :account, only: actions do
      resources :memberships, controller: 'account/memberships', only: [:index]
      resources :bugs, controller: 'account/bugs', only: :index
      resources :events, controller: 'account/events', only: :index
      resources :emails, controller: 'emails', only: [:index, :create, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
    end

    namespace :jira do
      resources :projects, only: :index
      resources :issues, only: :show
      resources :statuses, only: :index
    end unless Squash::Configuration.jira.disabled?

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'
    post 'signup' => 'users#create' if Squash::Configuration.authentication.strategy == 'password'

    get 'search/suggestions' => 'search#suggestions'
    get 'search' => 'search#search'

    # root to: 'projects#index'

  end
end

app/controllers/squash/account/bugs_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with the {Bug Bugs} {Watch watched} by the current
# {User}.

module Squash
  module Account

    class BugsController < SquashController
      # Number of Bugs to return per page.
      PER_PAGE = 50

      respond_to :json

      # Powers a table of a User's watched or assigned Bugs; returns a paginating
      # list of 50 Bugs, chosen according to the query parameters.
      #
      # Routes
      # ------
      #
      # * `GET /account/bugs.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                                                                                 |
      # |:-------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------|
      # | `type` | If `watched`, returns Bugs the User is watching. Otherwise, returns Bugs the User is assigned to.                                                               |
      # | `last` | The ID (`type` is `watched`) or number (`type` is not `watched`) of the last Bug of the previous page; used to determine the start of the next page (optional). |

      def index
        if params[:type].try!(:downcase) == 'watched'
          watches = current_user.watches.order('created_at DESC').includes(bug: [{environment: :project}, :assigned_user]).limit(PER_PAGE)
          last = params[:last].present? ? current_user.watches.joins(:bug).where(bug_id: params[:last]).first : nil
          watches = watches.where(infinite_scroll_clause('created_at', 'DESC', last, 'watches.bug_id')) if last
          @bugs = watches.map(&:bug)
        else
          @bugs = current_user.assigned_bugs.order('latest_occurrence DESC, bugs.number DESC').limit(PER_PAGE).includes(:assigned_user, environment: :project)
          last = params[:last].present? ? current_user.assigned_bugs.find_by_number(params[:last]) : nil
          @bugs = @bugs.where(infinite_scroll_clause('latest_occurrence', 'DESC', last, 'bugs.number')) if last
        end

        respond_with decorate(@bugs)
      end

      private

        def decorate(bugs)
          bugs.map do |bug|
            bug.as_json(only: [:number, :class_name, :message_template, :file, :line, :occurrences_count, :comments_count, :latest_occurrence]).merge(
                id:            bug.id, #TODO don't send the ID up to the view
                href:          project_environment_bug_url(bug.environment.project, bug.environment, bug),
                project:       bug.environment.project.as_json,
                environment:   bug.environment.as_json,
                assigned_user: bug.assigned_user.as_json,
                watch_url:     watch_project_environment_bug_url(bug.environment.project, bug.environment, bug, format: 'json')
            )
          end
        end

    end

  end
end

app/controllers/squash/account/events_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with {Event Events} of a {Bug} that the current {User}
# is {Watch watching}.

module Squash
  module Account
    class EventsController < SquashController
      include EventDecoration

      # Number of Events to return per page.
      PER_PAGE = 50

      respond_to :json

      # Returns a infinitely scrollable list of Events.
      #
      # Routes
      # ------
      #
      # * `GET /account/events.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                             |
      # |:-------|:------------------------------------------------------------------------------------------------------------|
      # | `last` | The number of the last Event of the previous page; used to determine the start of the next page (optional). |


      def index
        event_ids = current_user.user_events.order('created_at DESC').limit(PER_PAGE)
        last      = params[:last].present? ? current_user.user_events.find_by_event_id(params[:last]) : nil
        event_ids = event_ids.where(infinite_scroll_clause('created_at', 'DESC', last, 'event_id')) if last
        @events = Event.where(id: event_ids.pluck(:event_id)).order('created_at DESC').includes({user: :emails}, bug: {environment: {project: :slugs}})
        Event.preload @events.to_a

        respond_with decorate(@events)
      end

      protected

      # probably not the best way to do this
      def decorate(events)
        super.zip(events).map do |(hsh, event)|
          hsh.merge(
              bug:         event.bug.as_json.merge(
                               url: project_environment_bug_url(event.bug.environment.project, event.bug.environment, event.bug)
                           ),
              environment: event.bug.environment.as_json,
              project:     event.bug.environment.project.as_json
          )
        end
      end
    end
  end
end

app/controllers/squash/account/memberships_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with the {Membership Memberships} belonging to the
# current {User}.

module Squash
  module Account
    class MembershipsController < SquashController
      respond_to :json

      # Returns a list of the 10 most recent Project Memberships belonging to the
      # current User.
      #
      # Routes
      # ------
      #
      # * `GET /account/memberships.json`
      #
      # Query Parameters
      # ----------------
      #
      # |         |                                                                                                    |
      # |:--------|:---------------------------------------------------------------------------------------------------|
      # | `query` | If set, includes only those Memberships whose Project name begins with `query` (case-insensitive). |

      def index
        @memberships = current_user.memberships.order('memberships.created_at DESC').limit(10)
        @memberships = @memberships.project_prefix(params[:query]) if params[:query].present?
        # as much as i'd love to add includes(:project), it breaks the join in project_prefix.
        # go ahead, try it and see.

        render json: decorate(@memberships)
      end

      private

      def decorate(memberships)
        memberships.map do |membership|
          membership.as_json.deep_merge(
              project:        membership.project.as_json.merge(url: project_url(membership.project)),
              created_string: l(membership.created_at, format: :short_date),
              human_role:     membership.human_role.capitalize,
              role:           membership.role,
              url:            edit_project_my_membership_url(membership.project),
              delete_url:     project_my_membership_url(membership.project)
          )
        end
      end
    end
  end
end

app/helpers/squash_helper.rb
module SquashHelper

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a white background. Yields to render
  # content.
  def full_width_section(alt=false,&block)
    content_tag :div, class: "content-container#{alt ? '-alt' : ''}" do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, capture(&block), class: 'sixteen columns'
        end
      end
    end
  end

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a shaded background below a tabbed
  # header portion. The `tabs_proc` should render a `<UL>` with your tab
  # headers, and the `content_proc` should render the tab bodies. See
  # tabs.js.coffee for how to organize it.
  def tabbed_section(tabs_proc, content_proc)
    content_tag :div, class: 'tab-header-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, tabs_proc.(), class: 'sixteen columns'
         end
      end
    end
    content_tag :div, class: 'tab-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, content_proc.(), class: 'sixteen columns'
        end
      end
    end
  end

  def tab_header(&block)
    render 'squash/shared/tab_header', tab_header_content: capture(&block)
  end

  def tab_container(&block)
    render 'squash/shared/tab_container', tab_content: capture(&block)
  end

  # Call as part of {#body_content} to generate an inset, shaded
  # twelve-column content area simulating the appearance of a modal. Yields
  # to render content.
  def modal_section(&block)
    content_tag :div, class: 'content-container' do
      content_tag :div, class: 'container modal-container' do
        content_tag :div, class: 'row row-modal' do
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
          content_tag :div, capture(&block), class: 'twelve columns'
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
        end
      end
    end
  end

  def page_title
    @page_title
  end

  def breadcrumbs
    @breadcrumbs || []
  end

  def breadcrumbs_stats
    @breadcrumbs_stats || []
  end

  # def button_to(name, location, overrides={})
  #   button name, overrides.reverse_merge(href: location)
  # end

  def footer_portion
    footer do
      p { image_tag 'footer.png' }

      p do
        text "Hand-coded in San Francisco by Tim Morgan of "
        a "Square, Inc.", href: 'https://squareup.com'
      end
    end
  end

   # Composition of `pluralize` and `number_with_delimiter`.
  #
  # @param [Numeric] count The number of things.
  # @param [String] singular The name of the thing.
  # @param [String] plural The name of two of those things.
  # @return [String] Localized string describing the number and identity of the
  #   things.

  def pluralize_with_delimiter(count, singular, plural=nil)
    count ||= 0
    "#{number_with_delimiter count} " + ((count == 1 || count =~ /^1(\.0+)?$/) ? singular : (plural || singular.pluralize))
  end

  # Returns a link to a Project's commit (assuming the Project has a commit link
  # format specified). The title of the link will be the commit ID (abbreviated
  # if appropriate).
  #
  # If the commit URL cannot be determined, the full SHA1 is wrapped in a `CODE`
  # tag.
  #
  # @param [Project] project The project that the commit is to.
  # @param [String] commit The full ID of the commit.
  # @return [String] A link to the commit.

  def commit_link(project, commit)
    if url = project.commit_url(commit)
      link_to commit[0, 6], url
    else
      content_tag :tt, commit[0, 6]
    end
  end

  # Creates a link to open a project file in the user's editor. See the
  # editor_link.js.coffee file for more information.
  #
  # @param [String] editor The editor ("textmate", "sublime", "vim", or
  #   "emacs").
  # @param [Project] project The project containing the file.
  # @param [String] file The file path relative to the project root.
  # @param [String] line The line number within the file.

  def editor_link(editor, project, file, line)
    content_tag :a, '', :'data-editor' => editor, :'data-file' => file, :'data-line' => line, :'data-project' => project.to_param
  end

  # Converts a number in degrees decimal (DD) to degrees-minutes-seconds (DMS).
  #
  # @param [Float] coord The longitude or latitude, in degrees.
  # @param [:lat, :lon] axis The axis of the coordinate value.
  # @param [Hash] options Additional options.
  # @option options [Fixnum] :precision (2) The precision of the seconds value.
  # @return [String] Localized display of the DMS value.
  # @raise [ArgumentError] If an axis other than `:lat` or `:lon` is given.

  def number_to_dms(coord, axis, options={})
    positive = coord >= 0
    coord = coord.abs

    degrees = coord.floor
    remainder = coord - degrees
    minutes = (remainder*60).floor
    remainder -= minutes/60.0
    seconds = (remainder*60).round(options[:precision] || 2)

    hemisphere = case axis
                   when :lat
                     t("helpers.application.number_to_dms.#{positive ? 'north' : 'south'}")
                   when :lon
                     t("helpers.application.number_to_dms.#{positive ? 'east' : 'west'}")
                   else
                     raise ArgumentError, "axis must be :lat or :lon"
                 end

    t('helpers.application.number_to_dms.coordinate', degrees: degrees, minutes: minutes, seconds: seconds, hemisphere: hemisphere)
  end

  # Given the parts of a backtrace element, creates a single string displaying
  # them together in a typical backtrace format.
  #
  # @param [String] file The file path.
  # @param [Fixnum] line The line number in the file.
  # @param [String] method The method name.

  def format_backtrace_element(file, line, method=nil)
    str = "#{file}:#{line}"
    str << " (in `#{method}`)" if method
    str
  end

end

app/views/squash/shared/_breadcrumbs.html.slim
ul.breadcrumb
  - if crumbs.length > 1
    - 0.upto(crumbs.length - 2) do |i|
      li
        - if crumbs[i].kind_of?(String)
          span= crumbs[i]
        - else
          - options = {}
          - options[:show_environments] = true if crumbs[i].kind_of?(Project) # hacky hack hack
          - name = crumbs[i].kind_of?(Class) ? crumbs[i].model_name.human : crumbs[i].name
          - url_path = crumbs[0..i]
          - if url_path.last.kind_of?(Environment) # another hacky hack
            - name = url_path.last.name
            - url_path << Bug
          = link_to name, polymorphic_url(url_path, options)
      li.divider
  li.active= crumbs.last.kind_of?(String) ? crumbs.last : crumbs.last.name

app/views/squash/shared/_breadcrumbs_stats.html.slim
#breadcrumbs-stats
  - stats.each do |(number, singular, plural)|
    - plural ||= singular.pluralize
    .shown
      strong= number_with_delimiter(number)
      span= number == 1 ? singular : plural

app/views/squash/shared/_footer.html.slim
footer
  p
    = image_tag 'footer.png'
  p
    | Hand-coded in San Francisco by Tim Morgan of&nbsp;
    = link_to 'Square, Inc.', 'https://squareup.com'

app/views/squash/shared/_head.html.slim
meta[charset='utf-8']
meta[name='description' content="A Squarish bug reporting, analytics, and management tool."]
meta[name='author' content="Square, Inc."]
meta[name='viewport' content='width=device-width, initial-scale=1.0']
= favicon_link_tag
= csrf_meta_tags
title= page_title ? "Squash | #{page_title}" : "Squash: A Squarish exception tool"
= stylesheet_link_tag 'application'
= render 'squash/shared/inline_css'
/[if lt IE 9]
  = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
/[if lt IE 8]
  = javascript_include_tag 'flot/excanvas'

app/views/squash/shared/_inline_css.html.slim
- file_prefix = Rails.root.join 'app', 'views', params[:controller], params[:action]
- file = file_prefix + '.css'
= stylesheet_tag raw(File.read(file)) if File.exist?(file)
- file = file_prefix + '.css.erb'
= stylesheet_tag raw(ERB.new(File.read(file)).result(binding) if File.exist?(file)

app/views/squash/shared/_inline_javascript.html.slim
/ - file_prefix = Rails.root.join 'app', 'views', params[:controller]
/
/ - file = file_prefix.join "#{params[:action]}.js"
/ - if File.exist?(file)
/   = javascript_tag raw(File.read(file))
/
/ - file = file_prefix.join "#{params[:action]}.js.erb"
/ - Rails.logger.info "~~~~~~~~~~~~~~~~>> #{file}"
/ - if File.exist?(file)
/   = javascript_tag raw(ERB.new(File.read(file)).result(binding))

- asset = ::Rails.application.assets.find_asset(File.join(params[:controller],params[:action]+'.js'))
- if asset
 = javascript_tag asset.body

app/views/squash/shared/_navbar_environments.html.slim
li.with-dropdown
  = link_to (@environment ? @environment.name : "Environments" + content_tag(:i,'',class:'icon-chevron-down')).html_safe, "#navbar-envs-#{suffix}", rel: 'dropdown'
  ul.subnav[id="navbar-envs-#{suffix}"]
    - if @project.environments.empty?
      li= link_to 'No Environments', '#', class: 'disabled'
    - else
      li= link_to @project.default_environment.name, project_environment_bugs_url(@project, @project.default_environment) if @project.default_environment
      - @project.environments.order('name ASC').includes(:project).limit(20).each do |environment|
        - next if environment == @projecft.default_environment
        = link_to environment.name,  project_environment_bugs_url(@project, environment)
      li.divider
      li= link_to 'View All', project_url(@project, show_environments: 'true')

app/views/squash/shared/_navbar_large.html.slim
nav.container.full-size-only
  ul
    li#logo= link_to image_tag('bug.png')+" Squash".html_safe, root_url
    - if logged_in?
      = render 'squash/shared/navbar_projects', suffix: 'large'
      = render 'squash/shared/navbar_environments', suffix: 'large' if @project
      li#quicknav-container= search_field :q, id: 'quicknav', placeholder: 'Search'
      li= link_to 'My Account', account_url
      li= link_to content_tag(:i,nil,class:'icon-signout').html_safe, logout_url
    - else
      li#quicknav-container &nbsp;
      li= link_to 'Log In', login_url

app/views/squash/shared/_navbar_projects.html.slim
li.with-dropdown
  = link_to (@project ? @project.name : "Projects") + content_tag(:i,'',class:'icon-chevron-down'), "#navbar-projects-#{suffix}", rel: 'dropdown'
  ul.subnav[id="navbar-projects-#{suffix}"]
    - if current_user.memberships.count == 0
      / do nothing
    - elsif current_user.memberships.count > 10
      - current_user.memberships.order('created_at DESC').limit(10).includes(:project).map(&:project).each do |project|
        li= link_to project.name, project
      li= link_to 'More…', squash_projects_url
      li.divider
    - else
      - current_user.memberships.order('created_at DESC').includes(:project).map(&:project).each do |project|
        li= link_to project.name, project
      li.divider
    li= link_to current_user.memberships.count == 0 ? "All Projects" : "Other Project", squash_projects_url(anchor:'find')
    li
      = render 'squash/projects/new'

app/views/squash/shared/_navbar_small.html.slim
nav.container.compact-only
  ul
    li#logo= link_to image_tag('bug.png')+" Squash".html_safe, root_url
    - if logged_in?
      li#quicknav-container &nbsp;
      li= link_to content_tag(:i,'',class:'icon-signout').html_safe, logout_url
      li= link_to content_tag(:i,'',class:'icon-chevron-down').html_safe, '#expanded-nav', rel: 'dropdown'
    - else
      li#quicknav-container &nbsp;
      li=link_to content_tag(:i,'',class:'icon-signin').html_safe, login_url

- if logged_in?
  nav.container.compact-only#expanded-nav
    ul
      = render 'squash/shared/navbar_projects', suffix: 'small'
      = render 'squash/shared/navbar_environments', suffix: 'small' if @project
      li= link_to 'My Account', account_url

app/views/squash/shared/_tab_container.html.slim
.tabs-content
  = tab_content

app/views/squash/shared/_tab_header.html.slim
dl.tabs[data-tab]
  = tab_header_content