config/routes.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Rails.application.routes.draw do
  namespace 'squash', path: '' do
    # resources :projects, only: [ :new ]
    resources :projects do
      member { patch :rekey }
      resources :commits do
        member { get :context }
      end
      resources :environments, only: [ :index, :update ] do
        resources :bugs, except: [:new, :create, :edit] do
          collection { get :count }
          member { post :watch, :notify_deploy, :notify_occurrence }
          resources :occurrences, only: [:index, :show] do
            collection { get :count, :aggregate, :histogram }
          end
          resources :events, only: :index
          resources :comments, except: [:show, :new, :edit]
          resource :notification_threshold, only: [:create, :update, :destroy]
        end
      end
      resources :memberships, controller: 'project/memberships', only: [:index, :create, :update, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
      resource :membership, controller: 'project/membership', as: :my_membership, only: [:edit, :update, :destroy] do
        member { post :join }
        resources :emails, controller: 'emails', only: [:index, :create]
      end
    end

    constraints(id: /[^\/]+?/, format: 'html') do
      resources :users, only: :show
    end
    actions = [:index]
    actions << :create if Squash::Configuration.authentication.strategy == 'password'
    resources :users, only: actions

    actions = [:show]
    actions << :update if Squash::Configuration.authentication.strategy == 'password'
    resource :account, only: actions do
      resources :memberships, controller: 'account/memberships', only: [:index]
      resources :bugs, controller: 'account/bugs', only: :index
      resources :events, controller: 'account/events', only: :index
      resources :emails, controller: 'emails', only: [:index, :create, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
    end

    namespace :jira do
      resources :projects, only: :index
      resources :issues, only: :show
      resources :statuses, only: :index
    end unless Squash::Configuration.jira.disabled?

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'
    post 'signup' => 'users#create' if Squash::Configuration.authentication.strategy == 'password'

    get 'search/suggestions' => 'search#suggestions'
    get 'search' => 'search#search'

    # root to: 'projects#index'

  end
end

app/controllers/squash/account/bugs_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with the {Bug Bugs} {Watch watched} by the current
# {User}.

module Squash
  module Account

    class BugsController < SquashController
      # Number of Bugs to return per page.
      PER_PAGE = 50

      respond_to :json

      # Powers a table of a User's watched or assigned Bugs; returns a paginating
      # list of 50 Bugs, chosen according to the query parameters.
      #
      # Routes
      # ------
      #
      # * `GET /account/bugs.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                                                                                 |
      # |:-------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------|
      # | `type` | If `watched`, returns Bugs the User is watching. Otherwise, returns Bugs the User is assigned to.                                                               |
      # | `last` | The ID (`type` is `watched`) or number (`type` is not `watched`) of the last Bug of the previous page; used to determine the start of the next page (optional). |

      def index
        if params[:type].try!(:downcase) == 'watched'
          watches = current_user.watches.order('created_at DESC').includes(bug: [{environment: :project}, :assigned_user]).limit(PER_PAGE)
          last = params[:last].present? ? current_user.watches.joins(:bug).where(bug_id: params[:last]).first : nil
          watches = watches.where(infinite_scroll_clause('created_at', 'DESC', last, 'watches.bug_id')) if last
          @bugs = watches.map(&:bug)
        else
          @bugs = current_user.assigned_bugs.order('latest_occurrence DESC, bugs.number DESC').limit(PER_PAGE).includes(:assigned_user, environment: :project)
          last = params[:last].present? ? current_user.assigned_bugs.find_by_number(params[:last]) : nil
          @bugs = @bugs.where(infinite_scroll_clause('latest_occurrence', 'DESC', last, 'bugs.number')) if last
        end

        respond_with decorate(@bugs)
      end

      private

        def decorate(bugs)
          bugs.map do |bug|
            bug.as_json(only: [:number, :class_name, :message_template, :file, :line, :occurrences_count, :comments_count, :latest_occurrence]).merge(
                id:            bug.id, #TODO don't send the ID up to the view
                href:          project_environment_bug_url(bug.environment.project, bug.environment, bug),
                project:       bug.environment.project.as_json,
                environment:   bug.environment.as_json,
                assigned_user: bug.assigned_user.as_json,
                watch_url:     watch_project_environment_bug_url(bug.environment.project, bug.environment, bug, format: 'json')
            )
          end
        end

    end

  end
end

app/controllers/squash/account/events_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with {Event Events} of a {Bug} that the current {User}
# is {Watch watching}.

module Squash
  module Account
    class EventsController < SquashController
      include EventDecoration

      # Number of Events to return per page.
      PER_PAGE = 50

      respond_to :json

      # Returns a infinitely scrollable list of Events.
      #
      # Routes
      # ------
      #
      # * `GET /account/events.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                             |
      # |:-------|:------------------------------------------------------------------------------------------------------------|
      # | `last` | The number of the last Event of the previous page; used to determine the start of the next page (optional). |


      def index
        event_ids = current_user.user_events.order('created_at DESC').limit(PER_PAGE)
        last      = params[:last].present? ? current_user.user_events.find_by_event_id(params[:last]) : nil
        event_ids = event_ids.where(infinite_scroll_clause('created_at', 'DESC', last, 'event_id')) if last
        @events = Event.where(id: event_ids.pluck(:event_id)).order('created_at DESC').includes({user: :emails}, bug: {environment: {project: :slugs}})
        Event.preload @events.to_a

        respond_with decorate(@events)
      end

      protected

      # probably not the best way to do this
      def decorate(events)
        super.zip(events).map do |(hsh, event)|
          hsh.merge(
              bug:         event.bug.as_json.merge(
                               url: project_environment_bug_url(event.bug.environment.project, event.bug.environment, event.bug)
                           ),
              environment: event.bug.environment.as_json,
              project:     event.bug.environment.project.as_json
          )
        end
      end
    end
  end
end

app/controllers/squash/account/memberships_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with the {Membership Memberships} belonging to the
# current {User}.

module Squash
  module Account
    class MembershipsController < SquashController
      respond_to :json

      # Returns a list of the 10 most recent Project Memberships belonging to the
      # current User.
      #
      # Routes
      # ------
      #
      # * `GET /account/memberships.json`
      #
      # Query Parameters
      # ----------------
      #
      # |         |                                                                                                    |
      # |:--------|:---------------------------------------------------------------------------------------------------|
      # | `query` | If set, includes only those Memberships whose Project name begins with `query` (case-insensitive). |

      def index
        @memberships = current_user.memberships.order('memberships.created_at DESC').limit(10)
        @memberships = @memberships.project_prefix(params[:query]) if params[:query].present?
        # as much as i'd love to add includes(:project), it breaks the join in project_prefix.
        # go ahead, try it and see.

        render json: decorate(@memberships)
      end

      private

      def decorate(memberships)
        memberships.map do |membership|
          membership.as_json.deep_merge(
              project:        membership.project.as_json.merge(url: project_url(membership.project)),
              created_string: l(membership.created_at, format: :short_date),
              human_role:     membership.human_role.capitalize,
              role:           membership.role,
              url:            edit_project_my_membership_url(membership.project),
              delete_url:     project_my_membership_url(membership.project)
          )
        end
      end
    end
  end
end

app/helpers/squash_helper.rb
module SquashHelper

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a white background. Yields to render
  # content.
  def full_width_section(alt=false,&block)
    content_tag :div, class: "content-container#{alt ? '-alt' : ''}" do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, capture(&block), class: 'sixteen columns'
        end
      end
    end
  end

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a shaded background below a tabbed
  # header portion. The `tabs_proc` should render a `<UL>` with your tab
  # headers, and the `content_proc` should render the tab bodies. See
  # tabs.js.coffee for how to organize it.
  def tabbed_section(tabs_proc, content_proc)
    content_tag :div, class: 'tab-header-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, tabs_proc.(), class: 'sixteen columns'
         end
      end
    end
    content_tag :div, class: 'tab-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, content_proc.(), class: 'sixteen columns'
        end
      end
    end
  end

  def tab_header(&block)
    render 'squash/shared/tab_header', tab_header_content: capture(&block)
  end

  def tab_container(&block)
    render 'squash/shared/tab_container', tab_content: capture(&block)
  end

  # Call as part of {#body_content} to generate an inset, shaded
  # twelve-column content area simulating the appearance of a modal. Yields
  # to render content.
  def modal_section(&block)
    content_tag :div, class: 'content-container' do
      content_tag :div, class: 'container modal-container' do
        content_tag :div, class: 'row row-modal' do
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
          content_tag :div, capture(&block), class: 'twelve columns'
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
        end
      end
    end
  end

  def page_title
    @page_title
  end

  def breadcrumbs
    @breadcrumbs || []
  end

  def breadcrumbs_stats
    @breadcrumbs_stats || []
  end

  # def button_to(name, location, overrides={})
  #   button name, overrides.reverse_merge(href: location)
  # end

  def footer_portion
    footer do
      p { image_tag 'footer.png' }

      p do
        text "Hand-coded in San Francisco by Tim Morgan of "
        a "Square, Inc.", href: 'https://squareup.com'
      end
    end
  end

   # Composition of `pluralize` and `number_with_delimiter`.
  #
  # @param [Numeric] count The number of things.
  # @param [String] singular The name of the thing.
  # @param [String] plural The name of two of those things.
  # @return [String] Localized string describing the number and identity of the
  #   things.

  def pluralize_with_delimiter(count, singular, plural=nil)
    count ||= 0
    "#{number_with_delimiter count} " + ((count == 1 || count =~ /^1(\.0+)?$/) ? singular : (plural || singular.pluralize))
  end

  # Returns a link to a Project's commit (assuming the Project has a commit link
  # format specified). The title of the link will be the commit ID (abbreviated
  # if appropriate).
  #
  # If the commit URL cannot be determined, the full SHA1 is wrapped in a `CODE`
  # tag.
  #
  # @param [Project] project The project that the commit is to.
  # @param [String] commit The full ID of the commit.
  # @return [String] A link to the commit.

  def commit_link(project, commit)
    if url = project.commit_url(commit)
      link_to commit[0, 6], url
    else
      content_tag :tt, commit[0, 6]
    end
  end

  # Creates a link to open a project file in the user's editor. See the
  # editor_link.js.coffee file for more information.
  #
  # @param [String] editor The editor ("textmate", "sublime", "vim", or
  #   "emacs").
  # @param [Project] project The project containing the file.
  # @param [String] file The file path relative to the project root.
  # @param [String] line The line number within the file.

  def editor_link(editor, project, file, line)
    content_tag :a, '', :'data-editor' => editor, :'data-file' => file, :'data-line' => line, :'data-project' => project.to_param
  end

  # Converts a number in degrees decimal (DD) to degrees-minutes-seconds (DMS).
  #
  # @param [Float] coord The longitude or latitude, in degrees.
  # @param [:lat, :lon] axis The axis of the coordinate value.
  # @param [Hash] options Additional options.
  # @option options [Fixnum] :precision (2) The precision of the seconds value.
  # @return [String] Localized display of the DMS value.
  # @raise [ArgumentError] If an axis other than `:lat` or `:lon` is given.

  def number_to_dms(coord, axis, options={})
    positive = coord >= 0
    coord = coord.abs

    degrees = coord.floor
    remainder = coord - degrees
    minutes = (remainder*60).floor
    remainder -= minutes/60.0
    seconds = (remainder*60).round(options[:precision] || 2)

    hemisphere = case axis
                   when :lat
                     t("helpers.application.number_to_dms.#{positive ? 'north' : 'south'}")
                   when :lon
                     t("helpers.application.number_to_dms.#{positive ? 'east' : 'west'}")
                   else
                     raise ArgumentError, "axis must be :lat or :lon"
                 end

    t('helpers.application.number_to_dms.coordinate', degrees: degrees, minutes: minutes, seconds: seconds, hemisphere: hemisphere)
  end

  # Given the parts of a backtrace element, creates a single string displaying
  # them together in a typical backtrace format.
  #
  # @param [String] file The file path.
  # @param [Fixnum] line The line number in the file.
  # @param [String] method The method name.

  def format_backtrace_element(file, line, method=nil)
    str = "#{file}:#{line}"
    str << " (in `#{method}`)" if method
    str
  end

end

app/views/squash/bugs/_aggregation.html.slim
.inset-content
  form#aggregation-filter
    p Select up to four dimensions to analyze:
    #aggregation-options
      - 4.times do
        div
          = select_tag "dimensions[]", options_for_select(@aggregation_dimensions), id: nil
      #agg-submit= submit_tag "Go", class: 'default small'
  #aggregation-charts

app/views/squash/bugs/_blame.html.slim
- if @bug.blamed_commit
  - victims = @bug.blamed_users
  - if victims.any?
    p= "According to the VCS blame function, fault seems to lie with #{victims.map { |v| capture { mail_to v.email, (v.user.try!(:name) || v.email) } }.to_sentence}.*"
  = render 'squash/bugs/commit_summary', commit: @bug.blamed_commit
  - if victims.any?
    p.small &#42; The mailto link is not provided for purposes of sending hate mail.
  = render 'squash/bugs/diffs', id: 'blame', commit: @bug.blamed_commit
- else
  p= "According to the VCS blame function, commit #{commit_link(@project, @bug.blamed_revision)} seems to be at fault. This revision does not appear in the Git repository. (You might be able to fix this by refreshing the page.)"

app/views/squash/bugs/_comments.html.slim
.comment
  h5.comment-author
    = image_tag current_user.gravatar
    = link_to current_user.name, '#'
  = image_tag 'comment-arrow.png'
  .comment-body
    - url_parts = [@project, @environment, @bug, @bug.comments.build]
    = form_for url_parts, url: squash_project_environment_bug_comments_path(*url_parts) do |f|
      = f.text_area :body, rows: 4, cols: ''
        p= f.submit class: 'default'

#comments-list

app/views/squash/bugs/_commit_summary.html.slim
pre[class="brush: git; light: true"]
  = "commit #{commit.sha}"
  = "Author: #{commit.author.name} <#{commit.author.email}>"
  = "Date:   #{l commit.author.date, format: :git}"
  = ""
  = "        #{word_wrap commit.message}"

app/views/squash/bugs/_diffs.html.slim
- return unless commit.parents.size == 1
- diffs = @project.repo.diff(commit.parent, commit)
- return if diffs.size > 30 || diffs.size == 0

details.diff
  summary Diff
  dl.accordion[data-accordion]
    - diffs.each_with_index do |diff,i|
      = render 'squash/bugs/diff', diff: diff, id: id, index: i

app/views/squash/bugs/_fix.html.slim
- if !@bug.fixed?
  div.alert.important This bug was automatically reopened. Perhaps the fix below didn’t work?

- if @bug.resolution_commit
  = render 'squash/bugs/commit_summary', commit: @bug.resolution_commit
  = render 'squash/bugs/diffs', id: 'fix', commit: @bug.resolution_commit
- else
  p "This bug was fixed by commit #{commit_link(@project, @bug.resolution_revision)} . This revision does not appear in the Git repository. (You might be able to fix this by refreshing the page.)"

app/views/squash/bugs/_management.html.slim
p= content_tag :em, "How are things going with this bug?"

= form_for :bug, url: squash_project_environment_bug_path(@project, @environment, @bug), format: 'json', html: {class: 'labeled whitewashed', id: 'management-form'} do |f|
  fieldset
    h5 We're working on it.
    = f.label :assigned_user_id
    - members = @project.memberships.collect(&:user)
    - assigned_user_options = members.map { |u| [ u.name, u.id ] }
    = f.select :assigned_user_id, assigned_user_options, include_blank: true
    - unless Squash::Configuration.jira.disabled?
      div
        = f.label :jira_issue
        .field-group
          span.input-append
            = f.text_field :jira_issue, placeholder: "PROJECT-123", size: 14
            span.add-on#jira-status
          label[for='jira-projects'] or create new JIRA issue in
          select#jira-projects[name='jira-projects' disabled='disabled']
        p.help-block#jira-name
        = f.label :jira_status_id, "mark this bug as fixed once the issue is"
        = f.select :jira_status_id, [["Loading…", nil]], disabled: true
        p.help-block With this option, you can automatically close one or more bugs when a JIRA issue is resolved.

  fieldset
    h5 We fixed it.

    = f.label :fixed do
      = f.check_box :fixed
      span.checkbox-label This bug has been fixed

    = f.label :resolution_revision
    = f.text_field :resolution_revision, maxlength: 40

    = f.label :fix_deployed do
      = f.check_box :fix_deployed
      span.checkbox-label The fix for this bug has been deployed

  fieldset
    h5 It’s not really a bug; no one’s going to fix it.

    = f.label :irrelevant do
      = f.check_box :irrelevant
      span.checkbox-label Keep this bug, but don’t notify anyone about it

    p … or …

    = button_to "Delete this bug", squash_project_environment_bug_url(@project, @environment, @bug), 'data-sqmethod' => 'DELETE', class: 'warning', 'data-sqconfirm' => "Are you sure you want to delete this bug and all its occurrences?"
    - if @bug.duplicate?
      p.help-block This will remove all occurrences, comments, etc. Use for (e.g.) sensitive data or false notifications. All bugs marked as duplicate of this bug will be deleted as well.

  fieldset
    h5 It’s a duplicate of another bug.
    = f.label :duplicate_of_number
    .input-prepend
      span.add-on #
      = f.number_field :duplicate_of_number, disabled: @bug.duplicate?, class: 'input-small'
    - unless @bug.duplicate?
      p.help-block Make sure you enter the number correctly! This cannot be undone. All occurrences of this bug (past, present, and future) will be moved over to the bug you specify here.

  fieldset
    h5 … and I’d like to add a comment.
    .comment
      h6.comment-author
        = image_tag current_user.gravatar
        = link_to current_user.name, '#'
      = image_tag 'comment-arrow.png'
      .comment-body
        = f.fields_for @bug.comments.build do |nc|
          = nc.text_area :body, rows: 4, cols: '', id: nil

  .form-actions
    = f.submit class: 'default'

app/views/squash/bugs/_notifications.html.slim
form.labeled.whitewashed
  label
    = check_box_tag 'bug[notify_on_occurrence]', checked: @bug.notify_on_occurrence.include?(current_user.id), id: 'notify_on_occurrence'
    ' Email me whenever a new occurrence of this bug is recorded
  label
    = check_box_tag 'bug[notify_on_deploy]', checked: @bug.notify_on_deploy.include?(current_user.id), id: 'notify_on_deploy'
    ' Email me when the fix for this bug is deployed

- nt = current_user.notification_thresholds.find_by_bug_id(@bug.id) || Squash::NotificationThreshold.new
= form_for nt, url: squash_project_environment_bug_notification_threshold_url(@project, @environment, @bug, format: 'json'), html: {class: 'labeled whitewashed', id: 'notification-form'} do |f|
  fieldset
    h5 Notify me when this bug occurs a lot
    = f.label :threshold, "this many exceptions occur"
    = f.number_field :threshold, class: 'input-small'
    = f.label :period, "in this period of time"
    .field-group
      = f.number_field :period, class: 'input-small'
      ' seconds
    .form-actions
      = f.submit class: 'default'
      = button_to 'Remove', squash_project_environment_bug_notification_threshold_url(@project, @environment, @bug), :'data-sqmethod' => 'DELETE'

app/views/squash/bugs/_occurrences.html.slim
table#occurrences-table

app/views/squash/bugs/show.html.slim
= render 'squash/projects/header'

/ include Accordion
/ needs :project, :environment, :bug, :aggregation_dimensions, :new_issue_url
- @page_title = "Bug ##{number_with_delimiter @bug.number} (#{@project.name} #{@environment.name.capitalize})"
- @breadcrumbs = [ @project, @environment, @bug ]
- index_fields = Squash::OccurrencesController::INDEX_FIELDS[@bug.client].map { |key| [ key, Squash::Occurrence.human_attribute_name(key).titleize ] }.to_json

/ metric shit-ton of URLs
= hidden_field_tag 'bug-events-url', squash_project_environment_bug_events_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'commits-url', squash_project_commits_url(@project, format: 'json')
= hidden_field_tag 'comments-url', squash_project_environment_bug_comments_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'occurrences-url', squash_project_environment_bug_occurrences_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'watch-url', watch_squash_project_environment_bug_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'aggregate-occurrences-url', aggregate_squash_project_environment_bug_occurrences_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'notify-deploy-url', notify_deploy_squash_project_environment_bug_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'notify-occurrence-url', notify_occurrence_squash_project_environment_bug_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'histogram-occurence-url', histogram_squash_project_environment_bug_occurrences_url(@project, @environment, @bug, format: 'json')
= hidden_field_tag 'user-id', current_user.id
= hidden_field_tag 'user-role', current_user.role(@project)
= hidden_field_tag 'jira-issue-url', squash_jira_issue_url('REPLACEME')
= hidden_field_tag 'jira-statuses-url', squash_jira_projects_url(format: :json)
= hidden_field_tag 'jira-projects-url', squash_jira_statuses_url(format: :json)
= hidden_field_tag 'new-issue-url', @new_issue_url
= hidden_field_tag 'index-fields', index_fields
= hidden_field_tag 'jira-status-id', @bug.jira_status_id || ''

= full_width_section do
  / bug_title
  h1
    = @bug.class_name
    = link_to '', '#', class: "icon-star#{'-empty' unless current_user.watches?(@bug)}", alt: 'Watch/unwatch this bug'
  / notice_bars
  - if @bug.fixed?
    / fixed_bar
    .alert.success
      ' This bug has been marked as resolved.
      - if @bug.resolution_revision
        = "(#{commit_link(@project, @bug.resolution_revision)})"
      = "The fix has been deployed." if @bug.fix_deployed?
  - if @bug.duplicate?
    / duplicate_bar
    .alert.warning= "This bug is a duplicate of #{link_to '#'+number_with_delimiter(@bug.duplicate_of.number), project_environment_bug_url(@project, @environment, @bug.duplicate_of)}."
  - unless current_user.role(@bug)
    / uneditable_bar
    p.alert.info= "You will need to #{link_to "join this project", join_project_my_membership_url(@project), :'data-sqmethod' => 'POST', id: 'join-link'} to edit this bug."
  / bug_info
  h5 Message
  pre.scrollable= @bug.message_template

  = render 'squash/bugs/location'

  - if @bug.special_file?
    - case @bug.file # TODO don't guess, record this information
    - when /^0x/
      p.alert.info This bug has not been symbolicated. If you would like meaningful backtraces, please upload a symbolication file using your language’s client library.
    - when /^https?:\/\//
      p.alert.info No JavaScript source map was found for this bug. If you would like meaningful backtraces, please upload a source map using the Squash JavaScript client library.
    - when /\.java$/
      p.alert.info No Java renamelog was found for this bug. If you would like more meaningful backtraces, please upload a renamelog.xml file using the Squash Java deobfuscator.
    - else
      p.alert.error The backtraces for this bug cannot be displayed because they are in an unknown format.


dl.tabs[data-tab]
  dd.active= link_to "History", '#history', rel: 'tab'
  - if @bug.blamed_revision
    dd= link_to 'Git Blame', '#blame', rel: 'tab'
  - if @bug.resolution_revision
    dd= link_to 'The Fix', '#fix', rel: 'tab'
  - if current_user.role(@project)
    dd= link_to 'Management', '#management', rel: 'tab'
  dd= link_to 'Notifications', '#notifications', rel: 'tab'
  dd= link_to "Comments #{'('+number_with_delimiter(@bug.comments_count)+')' if @bug.comments_count > 0}", '#comments', rel: 'tab'
  dd= link_to 'Aggregation', '#aggregation', rel: 'tab'
  dd= link_to "Occurrences #{'('+number_with_delimiter(@bug.occurrences_count)+')' if @bug.occurrences_count > 0}", '#occurrences', rel: 'tab'

div.tabs-content
  .content.active#history= render 'squash/bugs/history'
  - if @bug.blamed_revision
    .content#blame= render 'squash/bugs/blame'
  - if @bug.resolution_revision
    .content#fix= render 'squash/bugs/fix'
  - if current_user.role(@project)
    .content#management= render 'squash/bugs/management'
  .content#notifications= render 'squash/bugs/notifications'
  .content#comments= render 'squash/bugs/comments'
  .content#aggregation= render 'squash/bugs/aggregation'
  .content#occurrences= render 'squash/bugs/occurrences'