config/routes.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Rails.application.routes.draw do
  namespace 'squash', path: '' do
    # resources :projects, only: [ :new ]
    resources :projects do
      member { patch :rekey }
      resources :commits do
        member { get :context }
      end
      resources :environments, only: [ :index, :update ] do
        resources :bugs, except: [:new, :create, :edit] do
          collection { get :count }
          member { post :watch, :notify_deploy, :notify_occurrence }
          resources :occurrences, only: [:index, :show] do
            collection { get :count, :aggregate, :histogram }
          end
          resources :events, only: :index
          resources :comments, except: [:show, :new, :edit]
          resource :notification_threshold, only: [:create, :update, :destroy]
        end
      end
      resources :memberships, controller: 'project/memberships', only: [:index, :create, :update, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
      resource :membership, controller: 'project/membership', as: :my_membership, only: [:edit, :update, :destroy] do
        member { post :join }
        resources :emails, controller: 'emails', only: [:index, :create]
      end
    end

    constraints(id: /[^\/]+?/, format: 'html') do
      resources :users, only: :show
    end
    actions = [:index]
    actions << :create if Squash::Configuration.authentication.strategy == 'password'
    resources :users, only: actions

    actions = [:show]
    actions << :update if Squash::Configuration.authentication.strategy == 'password'
    resource :account, only: actions do
      resources :memberships, controller: 'account/memberships', only: [:index]
      resources :bugs, controller: 'account/bugs', only: :index
      resources :events, controller: 'account/events', only: :index
      resources :emails, controller: 'emails', only: [:index, :create, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
    end

    namespace :jira do
      resources :projects, only: :index
      resources :issues, only: :show
      resources :statuses, only: :index
    end unless Squash::Configuration.jira.disabled?

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'
    post 'signup' => 'users#create' if Squash::Configuration.authentication.strategy == 'password'

    get 'search/suggestions' => 'search#suggestions'
    get 'search' => 'search#search'

    # root to: 'projects#index'

  end
end

app/controllers/jira/projects_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that loads JIRA projects.

class Jira::ProjectsController < ApplicationController
  skip_before_filter :login_required
  respond_to :json

  # Returns a list of JIRA projects.
  #
  # * `GET /jira/projects`

  def index
    @projects = Service::JIRA.projects
    respond_with(@projects) do |format|
      format.json { render json: @projects.to_a.sort_by(&:name).map(&:attrs).to_json }
    end
  end
end

app/controllers/squash/account/bugs_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with the {Bug Bugs} {Watch watched} by the current
# {User}.

module Squash
  module Account

    class BugsController < SquashController
      # Number of Bugs to return per page.
      PER_PAGE = 50

      respond_to :json

      # Powers a table of a User's watched or assigned Bugs; returns a paginating
      # list of 50 Bugs, chosen according to the query parameters.
      #
      # Routes
      # ------
      #
      # * `GET /account/bugs.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                                                                                 |
      # |:-------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------|
      # | `type` | If `watched`, returns Bugs the User is watching. Otherwise, returns Bugs the User is assigned to.                                                               |
      # | `last` | The ID (`type` is `watched`) or number (`type` is not `watched`) of the last Bug of the previous page; used to determine the start of the next page (optional). |

      def index
        if params[:type].try!(:downcase) == 'watched'
          watches = current_user.watches.order('created_at DESC').includes(bug: [{environment: :project}, :assigned_user]).limit(PER_PAGE)
          last = params[:last].present? ? current_user.watches.joins(:bug).where(bug_id: params[:last]).first : nil
          watches = watches.where(infinite_scroll_clause('created_at', 'DESC', last, 'watches.bug_id')) if last
          @bugs = watches.map(&:bug)
        else
          @bugs = current_user.assigned_bugs.order('latest_occurrence DESC, bugs.number DESC').limit(PER_PAGE).includes(:assigned_user, environment: :project)
          last = params[:last].present? ? current_user.assigned_bugs.find_by_number(params[:last]) : nil
          @bugs = @bugs.where(infinite_scroll_clause('latest_occurrence', 'DESC', last, 'bugs.number')) if last
        end

        respond_with decorate(@bugs)
      end

      private

        def decorate(bugs)
          bugs.map do |bug|
            bug.as_json(only: [:number, :class_name, :message_template, :file, :line, :occurrences_count, :comments_count, :latest_occurrence]).merge(
                id:            bug.id, #TODO don't send the ID up to the view
                href:          project_environment_bug_url(bug.environment.project, bug.environment, bug),
                project:       bug.environment.project.as_json,
                environment:   bug.environment.as_json,
                assigned_user: bug.assigned_user.as_json,
                watch_url:     watch_project_environment_bug_url(bug.environment.project, bug.environment, bug, format: 'json')
            )
          end
        end

    end

  end
end

app/controllers/squash/account/events_controller.rb
# Copyright 2013 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with {Event Events} of a {Bug} that the current {User}
# is {Watch watching}.

module Squash
  module Account
    class EventsController < SquashController
      include EventDecoration

      # Number of Events to return per page.
      PER_PAGE = 50

      respond_to :json

      # Returns a infinitely scrollable list of Events.
      #
      # Routes
      # ------
      #
      # * `GET /account/events.json`
      #
      # Query Parameters
      # ----------------
      #
      # |        |                                                                                                             |
      # |:-------|:------------------------------------------------------------------------------------------------------------|
      # | `last` | The number of the last Event of the previous page; used to determine the start of the next page (optional). |


      def index
        event_ids = current_user.user_events.order('created_at DESC').limit(PER_PAGE)
        last      = params[:last].present? ? current_user.user_events.find_by_event_id(params[:last]) : nil
        event_ids = event_ids.where(infinite_scroll_clause('created_at', 'DESC', last, 'event_id')) if last
        @events = Event.where(id: event_ids.pluck(:event_id)).order('created_at DESC').includes({user: :emails}, bug: {environment: {project: :slugs}})
        Event.preload @events.to_a

        respond_with decorate(@events)
      end

      protected

      # probably not the best way to do this
      def decorate(events)
        super.zip(events).map do |(hsh, event)|
          hsh.merge(
              bug:         event.bug.as_json.merge(
                               url: project_environment_bug_url(event.bug.environment.project, event.bug.environment, event.bug)
                           ),
              environment: event.bug.environment.as_json,
              project:     event.bug.environment.project.as_json
          )
        end
      end
    end
  end
end

app/helpers/squash_helper.rb
module SquashHelper

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a white background. Yields to render
  # content.
  def full_width_section(alt=false,&block)
    content_tag :div, class: "content-container#{alt ? '-alt' : ''}" do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, capture(&block), class: 'sixteen columns'
        end
      end
    end
  end

  # Call as part of {#body_content} to generate a full-width
  # (sixteen-column) content area with a shaded background below a tabbed
  # header portion. The `tabs_proc` should render a `<UL>` with your tab
  # headers, and the `content_proc` should render the tab bodies. See
  # tabs.js.coffee for how to organize it.
  def tabbed_section(tabs_proc, content_proc)
    content_tag :div, class: 'tab-header-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, tabs_proc.(), class: 'sixteen columns'
         end
      end
    end
    content_tag :div, class: 'tab-container' do
      content_tag :div, class: 'container' do
        content_tag :div, class: 'row' do
          content_tag :div, content_proc.(), class: 'sixteen columns'
        end
      end
    end
  end

  def tab_header(&block)
    render 'squash/shared/tab_header', tab_header_content: capture(&block)
  end

  def tab_container(&block)
    render 'squash/shared/tab_container', tab_content: capture(&block)
  end

  # Call as part of {#body_content} to generate an inset, shaded
  # twelve-column content area simulating the appearance of a modal. Yields
  # to render content.
  def modal_section(&block)
    content_tag :div, class: 'content-container' do
      content_tag :div, class: 'container modal-container' do
        content_tag :div, class: 'row row-modal' do
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
          content_tag :div, capture(&block), class: 'twelve columns'
          content_tag :div, '&nbsp;'.html_safe, class: 'two columns'
        end
      end
    end
  end

  def page_title
    @page_title
  end

  def breadcrumbs
    @breadcrumbs || []
  end

  def breadcrumbs_stats
    @breadcrumbs_stats || []
  end

  # def button_to(name, location, overrides={})
  #   button name, overrides.reverse_merge(href: location)
  # end

  def footer_portion
    footer do
      p { image_tag 'footer.png' }

      p do
        text "Hand-coded in San Francisco by Tim Morgan of "
        a "Square, Inc.", href: 'https://squareup.com'
      end
    end
  end

   # Composition of `pluralize` and `number_with_delimiter`.
  #
  # @param [Numeric] count The number of things.
  # @param [String] singular The name of the thing.
  # @param [String] plural The name of two of those things.
  # @return [String] Localized string describing the number and identity of the
  #   things.

  def pluralize_with_delimiter(count, singular, plural=nil)
    count ||= 0
    "#{number_with_delimiter count} " + ((count == 1 || count =~ /^1(\.0+)?$/) ? singular : (plural || singular.pluralize))
  end

  # Returns a link to a Project's commit (assuming the Project has a commit link
  # format specified). The title of the link will be the commit ID (abbreviated
  # if appropriate).
  #
  # If the commit URL cannot be determined, the full SHA1 is wrapped in a `CODE`
  # tag.
  #
  # @param [Project] project The project that the commit is to.
  # @param [String] commit The full ID of the commit.
  # @return [String] A link to the commit.

  def commit_link(project, commit)
    if url = project.commit_url(commit)
      link_to commit[0, 6], url
    else
      content_tag :tt, commit[0, 6]
    end
  end

  # Creates a link to open a project file in the user's editor. See the
  # editor_link.js.coffee file for more information.
  #
  # @param [String] editor The editor ("textmate", "sublime", "vim", or
  #   "emacs").
  # @param [Project] project The project containing the file.
  # @param [String] file The file path relative to the project root.
  # @param [String] line The line number within the file.

  def editor_link(editor, project, file, line)
    content_tag :a, '', :'data-editor' => editor, :'data-file' => file, :'data-line' => line, :'data-project' => project.to_param
  end

  # Converts a number in degrees decimal (DD) to degrees-minutes-seconds (DMS).
  #
  # @param [Float] coord The longitude or latitude, in degrees.
  # @param [:lat, :lon] axis The axis of the coordinate value.
  # @param [Hash] options Additional options.
  # @option options [Fixnum] :precision (2) The precision of the seconds value.
  # @return [String] Localized display of the DMS value.
  # @raise [ArgumentError] If an axis other than `:lat` or `:lon` is given.

  def number_to_dms(coord, axis, options={})
    positive = coord >= 0
    coord = coord.abs

    degrees = coord.floor
    remainder = coord - degrees
    minutes = (remainder*60).floor
    remainder -= minutes/60.0
    seconds = (remainder*60).round(options[:precision] || 2)

    hemisphere = case axis
                   when :lat
                     t("helpers.application.number_to_dms.#{positive ? 'north' : 'south'}")
                   when :lon
                     t("helpers.application.number_to_dms.#{positive ? 'east' : 'west'}")
                   else
                     raise ArgumentError, "axis must be :lat or :lon"
                 end

    t('helpers.application.number_to_dms.coordinate', degrees: degrees, minutes: minutes, seconds: seconds, hemisphere: hemisphere)
  end

  # Given the parts of a backtrace element, creates a single string displaying
  # them together in a typical backtrace format.
  #
  # @param [String] file The file path.
  # @param [Fixnum] line The line number in the file.
  # @param [String] method The method name.

  def format_backtrace_element(file, line, method=nil)
    str = "#{file}:#{line}"
    str << " (in `#{method}`)" if method
    str
  end

end

app/views/squash/projects/_environments_grid.html.slim
/ environments_grid
= full_width_section do
  - @project.environments.order('name ASC').limit(20).in_groups_of(2, nil) do |environments|
    .row
      - environments.each_with_index do |environment, idx|
        .six.columns
          div[class=(environment ? 'environment' : '')]
            - if environment
              h3= link_to environment.name, squash_project_environment_bugs_url(@project, environment)
              p.info
                = pluralize_with_delimiter(environment.bugs_count, 'bug')
                - if [:admin, :owner].include?(current_user.role(@project))
                  = " - "
                  span
                    - if @project.default_environment_id == environment.id
                      strong#default-indicator[data-id=environment.id] Default
                    - else
                      = link_to 'Make Default', '#', class: 'make-default', :'data-id' => environment.id
              - if [:admin, :owner].include?(current_user.role(@project))
                = form_for [@project, environment], url: squash_project_environment_url(@project,environment), format: 'json', namespace: "env_#{environment.name}" do |f|
                  p
                    = f.check_box :sends_emails
                    '
                    = f.label :sends_emails
                    - unless Squash::Configuration.pagerduty.disabled
                      '
                      = f.check_box :notifies_pagerduty
                      '
                      = f.label :notifies_pagerduty

app/views/squash/projects/_header.html.slim
h1= @project.name

app/views/squash/projects/_new.html.slim
- suffix = 'large' unless defined?(suffix)
= form_for current_user.owned_projects.build, as: :project, url: squash_projects_url(format: 'json'), id: "new_project-#{suffix}" do |f|
  h1 New Project
  = f.text_field :name, placeholder: ::Project.human_attribute_name(:name).titleize, required: true
  = f.text_field :repository_url, placeholder: ::Project.human_attribute_name(:repository_url).titleize.gsub('Url','URL'), required: true
  p.help-block
    strong Note:
    '  This is the URL you would use with git-clone, not the GitHub web page for the repository.
  = f.submit class: 'default'

app/views/squash/projects/index.js.erb
// Copyright 2013 Square Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

$(document).ready(function() {
  new PageManager().setup();
});

function PageManager() {
  this.setup = function() {
    this.setupWatchedBugsTable();
    this.setupAssignedBugsTable();
    this.setupMyFeed();
    this.setupFindAnyProject();
  };

  this.setupFindAnyProject = function() {
    new DynamicSearchField($('#find-project'), this.processAnyProjectSearchResults);
    this.processAnyProjectSearchResults(''); // pre-populate with most recent projects
  };

  this.processAnyProjectSearchResults = function(query) {
    var self = this;
    $.ajax('<%= squash_projects_url(format: 'json') %>?query=' + encodeURIComponent(query), {
      type:    'GET',
      success: function(results) {
        var resultList = $('#find-project-search-results');
        resultList.find('li').remove();
        $.each(results, function(_, project) {
          var li = $('<li/>').appendTo(resultList);
          var h5 = $('<h5/>').append($('<a/>').text(project.name).attr('href', project.url)).appendTo(li);

          if (project.role == null) {
            var btn = $("<button/>").text("Join").appendTo(h5);
            btn.click(function() {
              $.ajax(project.join_url, {
                type: 'POST',
                success: function() { self.processAnyProjectSearchResults(query); },
                error: function() { new Flash('alert').text("Couldn’t join project."); }
              });
            });
          }

          var p = $('<p/>').appendTo(li);
          switch (project.role) {
            case 'owner':
              $('<strong/>').text('Owner').appendTo(p);
              break;
            case 'admin':
              $('<strong/>').text('Administrator').appendTo(p);
              break;
            case 'member':
              $('<strong/>').text('Project member').appendTo(p);
              break;
            default:
              p.text("Owned by ");
              $('<a/>').text(project.owner.name).attr('href', project.owner.url).appendTo(p);
          }
          p.append(' — created ');
          $('<time/>').attr('datetime', project.created_at).appendTo(p).liveUpdate();
        });
      },
      error:   function() { new Flash('alert').text("Error retrieving search results."); }
    });
  };

  this.setupWatchedBugsTable = function() {
    var table = new SortableTable($('#watched-bugs'),
      "<%= account_bugs_url(format: 'json', type: 'watched') %>",
      [
        { key: 'project_and_environment', title: "Project", sortable: false, htmlGenerator: function(bug) {
          var span = $('<span/>').text(bug.environment.name);
          $('<br/>').prependTo(span);
          $('<strong/>').text(bug.project.name).prependTo(span);
          return span;
        } },
          { key: 'class_message', title: "Message", sortable: false, htmlGenerator: function(bug) {
            var sp = $('<span/>').addClass('long-words').text(bug.message_template);
            $('<br/>').prependTo(sp);
            $('<tt/>').text(bug.class_name).prependTo(sp);
            return sp;
          } },
        { title: "File", sortable: false, textGenerator: formatBugFile },
        { key: 'occurrences', title: "Counts", sortable: false, htmlGenerator: function(bug) {
          var sp = $('<span/>');
          sp.append(bug.occurrences_count);
          $('<i/>').addClass('icon-exclamation-sign').appendTo(sp);
          if (bug.comments_count > 0) {
            sp.append(' ' + bug.comments_count);
            $('<i/>').addClass('icon-comment').appendTo(sp);
          }
          return sp;
        } },
        { key: 'latest', title: "Latest", sortable: false, htmlGenerator: function(bug) {
          return $('<time/>').attr('datetime', bug.latest_occurrence).liveUpdate();
        } },
        { key: 'user_name', title: "Assigned To", sortable: false, textGenerator: function(bug) { return bug.assigned_user ? bug.assigned_user.name : "no one"; } },
        { key: 'unwatch', title: '', sortable: false, htmlGenerator: function(bug) {
          return $('<a/>').addClass('icon-star icon-large unwatch').attr('href', '#').click(function() {
            $.ajax(bug.watch_url, {
              type: 'POST',
              success: function() { table.refreshData(); },
              error: function() {
                new Flash('alert').text("Couldn’t unwatch that bug.");
                table.refreshData();
              },
              dataType: 'text'
            });
            return false;
          });
        } }
      ],
      {
        sort_key:    'latest',
        scroll_with: 'id'
      }
    ).refreshData();
  };

  this.setupAssignedBugsTable = function() {
      new SortableTable($('#assigned-bugs'),
                        "<%= squash_account_bugs_url(format: 'json') %>",
                        [
                          { key: 'project_and_environment', title: "Project", sortable: false, htmlGenerator: function(bug) {
                            var span = $('<span/>').text(bug.environment.name);
                            $('<br/>').prependTo(span);
                            $('<strong/>').text(bug.project.name).prependTo(span);
                            return span;
                          } },
                          { key: 'class_message', title: "Message", sortable: false, htmlGenerator: function(bug) {
                            var sp = $('<span/>').addClass('long-words').text(bug.message_template);
                            $('<br/>').prependTo(sp);
                            $('<tt/>').text(bug.class_name).prependTo(sp);
                            return sp;
                          } },
                          { title: "File", sortable: false, textGenerator: formatBugFile },
                          { key: 'occurrences', title: "Counts", sortable: false, htmlGenerator: function(bug) {
                            var sp = $('<span/>');
                            sp.append(bug.occurrences_count);
                            $('<i/>').addClass('icon-exclamation-sign').appendTo(sp);
                            if (bug.comments_count > 0) {
                              sp.append(' ' + bug.comments_count);
                              $('<i/>').addClass('icon-comment').appendTo(sp);
                            }
                            return sp;
                          } },
                          { key: 'latest', title: "Latest", sortable: false, htmlGenerator: function(bug) {
                            return $('<time/>').attr('datetime', bug.latest_occurrence).liveUpdate();
                          } },
                          { key: 'status', title: "Status", sortable: false, textGenerator: function(bug) {
                            switch (bug.status) {
                              case 'open': case 'assigned': return "unresolved";
                              case 'fixed': return "fixed";
                              case 'fix_deployed': return "fix deployed";
                            }
                          } }
                        ],
                        {
                          sort_key:    'latest',
                          scroll_with: 'id'
                        }
      ).refreshData();
    };

  this.setupMyFeed = function() {
    new Feed("<%= squash_account_events_url(format: 'json') %>", $('#events'), {bugHeader: true});
  };
}

app/views/squash/projects/show.html.slim
- @page_title = @project.name
- @breadcrumbs = [ @project ]

= render 'squash/projects/header'
= render 'squash/projects/environments_grid'

/ project_info
= full_width_section(true) do
  .row
    .four.columns
      / project_owner
      h5 Owner
      .profile-widget
        = image_tag @project.owner.gravatar
        h5= link_to @project.owner.name, respond_to?(:user_url) ? user_url(@project.owner) : squash_user_url(@project.owner)
        div
          strong= @project.owner.respond_to?(:username) ? @project.owner.username : @project.owner.name
        div.small= "Created #{l @project.created_at, format: :short_date}"
        div[style='clear:left;']

      / project_overview
      h5 Overview
      dl
        dt Environments
        dd= number_with_delimiter(@project.environments.count)
        dt Members
        dd
          = number_with_delimiter(@project.memberships.count)
          = "(#{pluralize_with_delimiter(@project.memberships.where(admin: true).count, 'administrator')})"

      h5 Settings
      p= link_to "Configure and install Squash", edit_squash_project_url(@project) if action_name == 'show'
      - if current_user.role(@project)
        p= link_to "Change membership settings", edit_squash_project_my_membership_url(@project)
      - else
        p= button_to "Join this team", join_squash_project_my_membership_url(@project), :'data-sqmethod' => 'POST'

    .twelve.columns
      h5 Members
      #members
      - if current_user.role(@project) == :owner
        / delete_project
        h5 Delete
        p
          strong Beware!
          ' Deleting this project will delete all environments, all bugs, all occurrences, all comments, and all other data.
        p= button_to "Delete", squash_project_url(@project), method: :delete, data: { confirm: "Are you SURE you want to delete the project #{@project.name}?" }, class: 'button radius alert small'
      - elsif !current_user.role(@project).nil?
        p= button_to 'Leave Project', squash_project_my_membership_url(@project), :'data-sqmethod' => 'DELETE', class: 'warning'

= javascript_tag do
  = render template: 'squash/projects/show.js.erb'

app/views/squash/projects/show.js.erb
// Copyright 2013 Square Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

$(document).ready(function() { new PageManager().setup(); });

function PageManager() {
  this.setup = function() {
    this.resetClickBinds();
    this.setupSendsEmailsCheckboxes();

    new MemberPanel($('#members'),
                    "<%= escape_javascript @project.name %>",
                    "<%= @project.to_param %>",
                    "<%= respond_to?(:users_path) ? users_path : squash_users_path %>",
                    "<%= squash_project_memberships_path(@project, format: 'json') %>",
                    "<%= squash_project_membership_path(@project, 'USERID', format: 'json') %>",
                    "<%= squash_project_path(@project, format: 'json') %>",
                    "<%= current_user.role(@project).to_s %>",
                    window.location.hash == '#change_owner');
  };

  this.setupSendsEmailsCheckboxes = function() {
    $('.environment form').each(function(_, formElement) {
      var form = new SmartForm($(formElement), function() {});
      $(formElement).find('input[type=checkbox]').click(function() { form.submit(); });
    });
  };

  this.resetClickBinds = function() {
    var self = this;
    $('a.make-default').click(function(e) {
      $.ajax("<%= squash_project_path @project, format: 'json' %>", {
        type: 'PATCH',
        data: $.param({
                        'project[default_environment_id]': $(e.currentTarget).data('id'),
                        '<%= request_forgery_protection_token %>': '<%= form_authenticity_token %>'
                      }),
        success: function() {
          // change Default to Make Default
          var parent = $('#default-indicator').parent();
          var id = $('#default-indicator').data('id');
          parent.empty();
          $('<a/>').text('Make default').attr({href: '#', 'data-id': id}).addClass('make-default').appendTo(parent);

          // change Make Default to Default
          parent = $(e.currentTarget).parent();
          id = $(e.currentTarget).data('id');
          parent.empty();
          $('<strong/>').text("Default").attr({'data-id': id, id: 'default-indicator'}).appendTo(parent);

          self.resetClickBinds();
        },
        error: function() { new Flash('alert').text("An error occurred when setting the default environment."); }
      });
    });
  };
}